---
name: ci_checks

on:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:

  ci:
    name: ci
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.x'
        check-latest: true

    - name: Check Go code formatting
      run: make check-fmt

    - name: Run Go linters
      uses: golangci/golangci-lint-action@v9

    - name: Build the app
      run: make build

